/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOWimp
#define ROOWimp

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TF1.h"
 
class RooWimp : public RooAbsPdf {
public:
  RooWimp() {} ; 
  RooWimp(const char *name, const char *title,
	      RooAbsReal& _Er,
	      RooAbsReal& _Mchi,
	      RooAbsReal& _sigma_nuc,
	      RooAbsReal& _A,
	      RooAbsReal& _v0,
	      RooAbsReal& _vesc);
  
  RooWimp(const RooWimp& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooWimp(*this,newname); }
  inline virtual ~RooWimp() { }

protected:

  RooRealProxy Er ;
  RooRealProxy Mchi ;
  RooRealProxy sigma_nuc ;
  RooRealProxy A ;
  RooRealProxy v0 ;
  RooRealProxy vesc ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooWimp,1) // Your description goes here...
};
 
#endif
