/********************************************************************
* EdwPulseDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EdwPulseDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEdwPulseDict();
extern void G__cpp_setup_inheritanceEdwPulseDict();
extern void G__cpp_setup_typetableEdwPulseDict();
extern void G__cpp_setup_memvarEdwPulseDict();
extern void G__cpp_setup_globalEdwPulseDict();
extern void G__cpp_setup_memfuncEdwPulseDict();
extern void G__cpp_setup_funcEdwPulseDict();
extern void G__set_cpp_environmentEdwPulseDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/EdwPulse.cc"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EdwPulseDictLN_TClass;
extern G__linked_taginfo G__EdwPulseDictLN_TBuffer;
extern G__linked_taginfo G__EdwPulseDictLN_TMemberInspector;
extern G__linked_taginfo G__EdwPulseDictLN_TObject;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_string;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EdwPulseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EdwPulseDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EdwPulseDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EdwPulseDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EdwPulseDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwPulseDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR;
extern G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwPulseDictLN_EdwPulse;

/* STUB derived class for protected member access */
