//
// File generated by rootcint at Fri Oct 31 11:01:39 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EdwPulseDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EdwPulseDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void EdwPulse_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EdwPulse(void *p = 0);
   static void *newArray_EdwPulse(Long_t size, void *p);
   static void delete_EdwPulse(void *p);
   static void deleteArray_EdwPulse(void *p);
   static void destruct_EdwPulse(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::EdwPulse*)
   {
      ::EdwPulse *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EdwPulse >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EdwPulse", ::EdwPulse::Class_Version(), "./../src/EdwPulse.h", 6,
                  typeid(::EdwPulse), DefineBehavior(ptr, ptr),
                  &::EdwPulse::Dictionary, isa_proxy, 4,
                  sizeof(::EdwPulse) );
      instance.SetNew(&new_EdwPulse);
      instance.SetNewArray(&newArray_EdwPulse);
      instance.SetDelete(&delete_EdwPulse);
      instance.SetDeleteArray(&deleteArray_EdwPulse);
      instance.SetDestructor(&destruct_EdwPulse);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::EdwPulse*)
   {
      return GenerateInitInstanceLocal((::EdwPulse*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EdwPulse*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *EdwPulse::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *EdwPulse::Class_Name()
{
   return "EdwPulse";
}

//______________________________________________________________________________
const char *EdwPulse::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::EdwPulse*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EdwPulse::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::EdwPulse*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EdwPulse::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::EdwPulse*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EdwPulse::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::EdwPulse*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void EdwPulse::Streamer(TBuffer &R__b)
{
   // Stream an object of class EdwPulse.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(EdwPulse::Class(),this);
   } else {
      R__b.WriteClassBuffer(EdwPulse::Class(),this);
   }
}

//______________________________________________________________________________
void EdwPulse::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EdwPulse.
      TClass *R__cl = ::EdwPulse::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fChannel", (void*)&fChannel);
      R__insp.InspectMember("string", (void*)&fChannel, "fChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fIsHeat", &fIsHeat);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fIsBBv2", &fIsBBv2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fIsTrig", &fIsTrig);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSampling_ms", &fSampling_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPretrigger", &fPretrigger);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTrace", (void*)&fTrace);
      R__insp.InspectMember("vector<Short_t>", (void*)&fTrace, "fTrace.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTraceLength", &fTraceLength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPatternLength", &fPatternLength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSign", &fSign);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fModulationLength", &fModulationLength);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_EdwPulse(void *p) {
      return  p ? new(p) ::EdwPulse : new ::EdwPulse;
   }
   static void *newArray_EdwPulse(Long_t nElements, void *p) {
      return p ? new(p) ::EdwPulse[nElements] : new ::EdwPulse[nElements];
   }
   // Wrapper around operator delete
   static void delete_EdwPulse(void *p) {
      delete ((::EdwPulse*)p);
   }
   static void deleteArray_EdwPulse(void *p) {
      delete [] ((::EdwPulse*)p);
   }
   static void destruct_EdwPulse(void *p) {
      typedef ::EdwPulse current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::EdwPulse

namespace ROOT {
   void vectorlEshortgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEshortgR_Dictionary();
   static void *new_vectorlEshortgR(void *p = 0);
   static void *newArray_vectorlEshortgR(Long_t size, void *p);
   static void delete_vectorlEshortgR(void *p);
   static void deleteArray_vectorlEshortgR(void *p);
   static void destruct_vectorlEshortgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<short>*)
   {
      vector<short> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<short>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<short>", -2, "vector.dll", 0,
                  typeid(vector<short>), DefineBehavior(ptr, ptr),
                  0, &vectorlEshortgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<short>) );
      instance.SetNew(&new_vectorlEshortgR);
      instance.SetNewArray(&newArray_vectorlEshortgR);
      instance.SetDelete(&delete_vectorlEshortgR);
      instance.SetDeleteArray(&deleteArray_vectorlEshortgR);
      instance.SetDestructor(&destruct_vectorlEshortgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<short> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<short>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEshortgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<short>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEshortgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short> : new vector<short>;
   }
   static void *newArray_vectorlEshortgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short>[nElements] : new vector<short>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEshortgR(void *p) {
      delete ((vector<short>*)p);
   }
   static void deleteArray_vectorlEshortgR(void *p) {
      delete [] ((vector<short>*)p);
   }
   static void destruct_vectorlEshortgR(void *p) {
      typedef vector<short> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<short>

/********************************************************
* EdwPulseDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEdwPulseDict();

extern "C" void G__set_cpp_environmentEdwPulseDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../src/EdwPulse.cc");
  G__cpp_reset_tagtableEdwPulseDict();
}
#include <new>
extern "C" int G__cpp_dllrevEdwPulseDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EdwPulse */
static int G__EdwPulseDict_670_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdwPulse* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdwPulse[n];
     } else {
       p = new((void*) gvp) EdwPulse[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdwPulse;
     } else {
       p = new((void*) gvp) EdwPulse;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EdwPulseDictLN_EdwPulse));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string* pobj;
         const string xobj = ((const EdwPulse*) G__getstructoffset())->Channel();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<Short_t>* pobj;
         const vector<Short_t> xobj = ((const EdwPulse*) G__getstructoffset())->Trace();
         pobj = new vector<Short_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const EdwPulse*) G__getstructoffset())->TraceLength());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const EdwPulse*) G__getstructoffset())->Trace((Short_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const EdwPulse*) G__getstructoffset())->Pretrigger());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const EdwPulse*) G__getstructoffset())->Sampling_ms());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetChannel(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetSampling_ms((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetPretrigger((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetTrace(*(vector<Short_t>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetTrace((UShort_t) G__int(libp->para[0]), (const Short_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((EdwPulse*) G__getstructoffset())->IsSaturated());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const EdwPulse*) G__getstructoffset())->IsHeat());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const EdwPulse*) G__getstructoffset())->IsBBv2());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const EdwPulse*) G__getstructoffset())->IsTrig());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetSign((Short_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const EdwPulse*) G__getstructoffset())->Sign());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetPatternLength((UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const EdwPulse*) G__getstructoffset())->PatternLength());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetModulationLength((UShort_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const EdwPulse*) G__getstructoffset())->ModulationLength());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetBBv2Flag((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->SetTriggerFlag((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EdwPulse::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdwPulse::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EdwPulse::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EdwPulse::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwPulse*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdwPulse::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdwPulse::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdwPulse::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwPulseDict_670_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdwPulse::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EdwPulseDict_670_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EdwPulse* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EdwPulse(*(EdwPulse*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EdwPulseDictLN_EdwPulse));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EdwPulse G__TEdwPulse;
static int G__EdwPulseDict_670_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EdwPulse*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EdwPulse*) (soff+(sizeof(EdwPulse)*i)))->~G__TEdwPulse();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EdwPulse*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EdwPulse*) (soff))->~G__TEdwPulse();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EdwPulseDict_670_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdwPulse* dest = (EdwPulse*) G__getstructoffset();
   *dest = *(EdwPulse*) libp->para[0].ref;
   const EdwPulse& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EdwPulse */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEdwPulseDict {
 public:
  G__Sizep2memfuncEdwPulseDict(): p(&G__Sizep2memfuncEdwPulseDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEdwPulseDict::*p)();
};

size_t G__get_sizep2memfuncEdwPulseDict()
{
  G__Sizep2memfuncEdwPulseDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEdwPulseDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EdwPulseDictLN_EdwPulse))) {
     EdwPulse *G__Lderived;
     G__Lderived=(EdwPulse*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EdwPulseDictLN_EdwPulse),G__get_linked_tagnum(&G__EdwPulseDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEdwPulseDict() {

   /* Setting up typedef entry */
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__EdwPulseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BoloStr>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RunStr>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PeriodStr>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TemplateStr>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Short_t>",117,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEshortcOallocatorlEshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EdwPulse */
static void G__setup_memvarEdwPulse(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EdwPulseDictLN_EdwPulse));
   { EdwPulse *p; p=(EdwPulse*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwPulseDictLN_string),-1,-1,2,"fChannel=",0,"*< Channel */");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fIsHeat=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fIsBBv2=",0,"*< Specific to ion: RC vs Heavyside shape */");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fIsTrig=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fSampling_ms=",0,"*< Sampling frequency */");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fPretrigger=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEshortcOallocatorlEshortgRsPgR),G__defined_typename("vector<Short_t>"),-1,2,"fTrace=",0,"*< Raw trace */");
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,2,"fTraceLength=",0,(char*)NULL);
   G__memvar_setup((void*)0,114,0,0,-1,G__defined_typename("UShort_t"),-1,2,"fPatternLength=",0,"*< Pattern */");
   G__memvar_setup((void*)0,115,0,0,-1,G__defined_typename("Short_t"),-1,2,"fSign=",0,"*< Pulse sign (defined a priori) */");
   G__memvar_setup((void*)0,114,0,0,-1,G__defined_typename("UShort_t"),-1,2,"fModulationLength=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EdwPulseDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEdwPulseDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEdwPulse(void) {
   /* EdwPulse */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EdwPulseDictLN_EdwPulse));
   G__memfunc_setup("EdwPulse",809,G__EdwPulseDict_670_0_1, 105, G__get_linked_tagnum(&G__EdwPulseDictLN_EdwPulse), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__EdwPulseDict_670_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Channel",697,G__EdwPulseDict_670_0_3, 117, G__get_linked_tagnum(&G__EdwPulseDictLN_string), -1, 0, 0, 1, 1, 8, "", "*< Channel */", (void*) NULL, 0);
   G__memfunc_setup("Trace",495,G__EdwPulseDict_670_0_4, 117, G__get_linked_tagnum(&G__EdwPulseDictLN_vectorlEshortcOallocatorlEshortgRsPgR), G__defined_typename("vector<Short_t>"), 0, 0, 1, 1, 8, "", "*< Raw trace (short type) */", (void*) NULL, 0);
   G__memfunc_setup("TraceLength",1105,G__EdwPulseDict_670_0_5, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 8, "", "*< Trace size */", (void*) NULL, 0);
   G__memfunc_setup("Trace",495,G__EdwPulseDict_670_0_6, 115, -1, G__defined_typename("Short_t"), 0, 1, 1, 1, 8, "s - 'Short_t' 0 - pt", "*< Raw trace */", (void*) NULL, 0);
   G__memfunc_setup("Pretrigger",1051,G__EdwPulseDict_670_0_7, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Sampling_ms",1146,G__EdwPulseDict_670_0_8, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", "*< Sampling frequency */", (void*) NULL, 0);
   G__memfunc_setup("SetChannel",997,G__EdwPulseDict_670_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - aChannel", "*< Channel */", (void*) NULL, 0);
   G__memfunc_setup("SetSampling_ms",1446,G__EdwPulseDict_670_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - aSampling", "*< Sampling frequency */", (void*) NULL, 0);
   G__memfunc_setup("SetPretrigger",1351,G__EdwPulseDict_670_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - pretrig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTrace",795,G__EdwPulseDict_670_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<short,allocator<short> >' 'vector<Short_t>' 11 - aTrace", "*< Trace */", (void*) NULL, 0);
   G__memfunc_setup("SetTrace",795,G__EdwPulseDict_670_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"r - 'UShort_t' 0 - n S - 'Short_t' 10 - aData", "*< Trace */", (void*) NULL, 0);
   G__memfunc_setup("IsSaturated",1129,G__EdwPulseDict_670_0_14, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", "*< Returns 1 if the trace (of short type) reaches saturation */", (void*) NULL, 0);
   G__memfunc_setup("IsHeat",574,G__EdwPulseDict_670_0_15, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsBBv2",488,G__EdwPulseDict_670_0_16, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsTrig",594,G__EdwPulseDict_670_0_17, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSign",701,G__EdwPulseDict_670_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "s - 'Short_t' 0 - aSign", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Sign",401,G__EdwPulseDict_670_0_19, 115, -1, G__defined_typename("Short_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPatternLength",1644,G__EdwPulseDict_670_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 0 - aPattLen", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PatternLength",1344,G__EdwPulseDict_670_0_21, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetModulationLength",1962,G__EdwPulseDict_670_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "r - 'UShort_t' 0 - aMod", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ModulationLength",1662,G__EdwPulseDict_670_0_23, 114, -1, G__defined_typename("UShort_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetBBv2Flag",978,G__EdwPulseDict_670_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - isbbv2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTriggerFlag",1402,G__EdwPulseDict_670_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - istrig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__EdwPulseDict_670_0_26, 85, G__get_linked_tagnum(&G__EdwPulseDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EdwPulse::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EdwPulseDict_670_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdwPulse::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EdwPulseDict_670_0_28, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EdwPulse::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EdwPulseDict_670_0_29, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EdwPulse::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EdwPulseDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EdwPulseDict_670_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EdwPulseDict_670_0_34, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdwPulse::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EdwPulseDict_670_0_35, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdwPulse::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EdwPulseDict_670_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdwPulse::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EdwPulseDict_670_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdwPulse::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("EdwPulse", 809, G__EdwPulseDict_670_0_38, (int) ('i'), G__get_linked_tagnum(&G__EdwPulseDictLN_EdwPulse), -1, 0, 1, 1, 1, 0, "u 'EdwPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EdwPulse", 935, G__EdwPulseDict_670_0_39, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EdwPulseDict_670_0_40, (int) ('u'), G__get_linked_tagnum(&G__EdwPulseDictLN_EdwPulse), -1, 1, 1, 1, 1, 0, "u 'EdwPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEdwPulseDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEdwPulseDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEdwPulseDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EdwPulseDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EdwPulseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR = { "vector<BoloStr,allocator<BoloStr> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BoloStr,allocator<BoloStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR = { "vector<RunStr,allocator<RunStr> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<RunStr,allocator<RunStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR = { "vector<PeriodStr,allocator<PeriodStr> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<PeriodStr,allocator<PeriodStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR = { "vector<TemplateStr,allocator<TemplateStr> >" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TemplateStr,allocator<TemplateStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwPulseDictLN_EdwPulse = { "EdwPulse" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEdwPulseDict() {
  G__EdwPulseDictLN_TClass.tagnum = -1 ;
  G__EdwPulseDictLN_TBuffer.tagnum = -1 ;
  G__EdwPulseDictLN_TMemberInspector.tagnum = -1 ;
  G__EdwPulseDictLN_TObject.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_string.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EdwPulseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EdwPulseDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EdwPulseDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EdwPulseDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EdwPulseDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwPulseDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR.tagnum = -1 ;
  G__EdwPulseDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwPulseDictLN_EdwPulse.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEdwPulseDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_string);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EdwPulseDictLN_EdwPulse),sizeof(EdwPulse),-1,292096,(char*)NULL,G__setup_memvarEdwPulse,G__setup_memfuncEdwPulse);
}
extern "C" void G__cpp_setupEdwPulseDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEdwPulseDict()");
  G__set_cpp_environmentEdwPulseDict();
  G__cpp_setup_tagtableEdwPulseDict();

  G__cpp_setup_inheritanceEdwPulseDict();

  G__cpp_setup_typetableEdwPulseDict();

  G__cpp_setup_memvarEdwPulseDict();

  G__cpp_setup_memfuncEdwPulseDict();
  G__cpp_setup_globalEdwPulseDict();
  G__cpp_setup_funcEdwPulseDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEdwPulseDict();
  return;
}
class G__cpp_setup_initEdwPulseDict {
  public:
    G__cpp_setup_initEdwPulseDict() { G__add_setup_func("EdwPulseDict",(G__incsetup)(&G__cpp_setupEdwPulseDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEdwPulseDict() { G__remove_setup_func("EdwPulseDict"); }
};
G__cpp_setup_initEdwPulseDict G__cpp_setup_initializerEdwPulseDict;

