//
// File generated by rootcint at Fri Oct 31 11:01:42 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EdwTemplateDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EdwTemplateDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void EdwTemplate_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EdwTemplate(void *p = 0);
   static void *newArray_EdwTemplate(Long_t size, void *p);
   static void delete_EdwTemplate(void *p);
   static void deleteArray_EdwTemplate(void *p);
   static void destruct_EdwTemplate(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::EdwTemplate*)
   {
      ::EdwTemplate *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EdwTemplate >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EdwTemplate", ::EdwTemplate::Class_Version(), "./../src/EdwTemplate.h", 7,
                  typeid(::EdwTemplate), DefineBehavior(ptr, ptr),
                  &::EdwTemplate::Dictionary, isa_proxy, 4,
                  sizeof(::EdwTemplate) );
      instance.SetNew(&new_EdwTemplate);
      instance.SetNewArray(&newArray_EdwTemplate);
      instance.SetDelete(&delete_EdwTemplate);
      instance.SetDeleteArray(&deleteArray_EdwTemplate);
      instance.SetDestructor(&destruct_EdwTemplate);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::EdwTemplate*)
   {
      return GenerateInitInstanceLocal((::EdwTemplate*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EdwTemplate*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *EdwTemplate::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *EdwTemplate::Class_Name()
{
   return "EdwTemplate";
}

//______________________________________________________________________________
const char *EdwTemplate::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::EdwTemplate*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EdwTemplate::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::EdwTemplate*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EdwTemplate::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::EdwTemplate*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EdwTemplate::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::EdwTemplate*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void EdwTemplate::Streamer(TBuffer &R__b)
{
   // Stream an object of class EdwTemplate.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(EdwTemplate::Class(),this);
   } else {
      R__b.WriteClassBuffer(EdwTemplate::Class(),this);
   }
}

//______________________________________________________________________________
void EdwTemplate::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EdwTemplate.
      TClass *R__cl = ::EdwTemplate::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fChannel", (void*)&fChannel);
      R__insp.InspectMember("string", (void*)&fChannel, "fChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fType", (void*)&fType);
      R__insp.InspectMember("string", (void*)&fType, "fType.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fStartValidity", &fStartValidity);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEndValidity", &fEndValidity);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPretrigger", &fPretrigger);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTraceLength", &fTraceLength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSign", &fSign);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNormalisation", &fNormalisation);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCoefficients", (void*)&fCoefficients);
      R__insp.InspectMember("vector<Float_t>", (void*)&fCoefficients, "fCoefficients.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTrace", (void*)&fTrace);
      R__insp.InspectMember("vector<Float_t>", (void*)&fTrace, "fTrace.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBinsOffsetFFT", (void*)&fBinsOffsetFFT);
      R__insp.InspectMember("vector<Int_t>", (void*)&fBinsOffsetFFT, "fBinsOffsetFFT.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTracesOffsetFFT", (void*)&fTracesOffsetFFT);
      R__insp.InspectMember("vector<vector<Float_t> >", (void*)&fTracesOffsetFFT, "fTracesOffsetFFT.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDenoms", (void*)&fDenoms);
      R__insp.InspectMember("vector<Float_t>", (void*)&fDenoms, "fDenoms.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fKernels", (void*)&fKernels);
      R__insp.InspectMember("vector<vector<Float_t> >", (void*)&fKernels, "fKernels.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_EdwTemplate(void *p) {
      return  p ? new(p) ::EdwTemplate : new ::EdwTemplate;
   }
   static void *newArray_EdwTemplate(Long_t nElements, void *p) {
      return p ? new(p) ::EdwTemplate[nElements] : new ::EdwTemplate[nElements];
   }
   // Wrapper around operator delete
   static void delete_EdwTemplate(void *p) {
      delete ((::EdwTemplate*)p);
   }
   static void deleteArray_EdwTemplate(void *p) {
      delete [] ((::EdwTemplate*)p);
   }
   static void destruct_EdwTemplate(void *p) {
      typedef ::EdwTemplate current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::EdwTemplate

namespace ROOT {
   void vectorlEfloatgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEfloatgR_Dictionary();
   static void *new_vectorlEfloatgR(void *p = 0);
   static void *newArray_vectorlEfloatgR(Long_t size, void *p);
   static void delete_vectorlEfloatgR(void *p);
   static void deleteArray_vectorlEfloatgR(void *p);
   static void destruct_vectorlEfloatgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<float>*)
   {
      vector<float> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<float>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<float>", -2, "vector.dll", 0,
                  typeid(vector<float>), DefineBehavior(ptr, ptr),
                  0, &vectorlEfloatgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<float>) );
      instance.SetNew(&new_vectorlEfloatgR);
      instance.SetNewArray(&newArray_vectorlEfloatgR);
      instance.SetDelete(&delete_vectorlEfloatgR);
      instance.SetDeleteArray(&deleteArray_vectorlEfloatgR);
      instance.SetDestructor(&destruct_vectorlEfloatgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<float> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<float>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEfloatgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<float>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEfloatgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float> : new vector<float>;
   }
   static void *newArray_vectorlEfloatgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float>[nElements] : new vector<float>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEfloatgR(void *p) {
      delete ((vector<float>*)p);
   }
   static void deleteArray_vectorlEfloatgR(void *p) {
      delete [] ((vector<float>*)p);
   }
   static void destruct_vectorlEfloatgR(void *p) {
      typedef vector<float> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<float>

namespace ROOT {
   void vectorlEintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEintgR_Dictionary();
   static void *new_vectorlEintgR(void *p = 0);
   static void *newArray_vectorlEintgR(Long_t size, void *p);
   static void delete_vectorlEintgR(void *p);
   static void deleteArray_vectorlEintgR(void *p);
   static void destruct_vectorlEintgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<int>*)
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<int>", -2, "prec_stl/vector", 49,
                  typeid(vector<int>), DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEintgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
   static void *newArray_vectorlEintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEintgR(void *p) {
      delete ((vector<int>*)p);
   }
   static void deleteArray_vectorlEintgR(void *p) {
      delete [] ((vector<int>*)p);
   }
   static void destruct_vectorlEintgR(void *p) {
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<int>

namespace ROOT {
   void vectorlEvectorlEfloatgRsPgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEvectorlEfloatgRsPgR_Dictionary();
   static void *new_vectorlEvectorlEfloatgRsPgR(void *p = 0);
   static void *newArray_vectorlEvectorlEfloatgRsPgR(Long_t size, void *p);
   static void delete_vectorlEvectorlEfloatgRsPgR(void *p);
   static void deleteArray_vectorlEvectorlEfloatgRsPgR(void *p);
   static void destruct_vectorlEvectorlEfloatgRsPgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<vector<float> >*)
   {
      vector<vector<float> > *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<vector<float> >),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<vector<float> >", -2, "prec_stl/vector", 49,
                  typeid(vector<vector<float> >), DefineBehavior(ptr, ptr),
                  0, &vectorlEvectorlEfloatgRsPgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<vector<float> >) );
      instance.SetNew(&new_vectorlEvectorlEfloatgRsPgR);
      instance.SetNewArray(&newArray_vectorlEvectorlEfloatgRsPgR);
      instance.SetDelete(&delete_vectorlEvectorlEfloatgRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEvectorlEfloatgRsPgR);
      instance.SetDestructor(&destruct_vectorlEvectorlEfloatgRsPgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<vector<float> > >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<vector<float> >*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEvectorlEfloatgRsPgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<vector<float> >*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEvectorlEfloatgRsPgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<float> > : new vector<vector<float> >;
   }
   static void *newArray_vectorlEvectorlEfloatgRsPgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<float> >[nElements] : new vector<vector<float> >[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEvectorlEfloatgRsPgR(void *p) {
      delete ((vector<vector<float> >*)p);
   }
   static void deleteArray_vectorlEvectorlEfloatgRsPgR(void *p) {
      delete [] ((vector<vector<float> >*)p);
   }
   static void destruct_vectorlEvectorlEfloatgRsPgR(void *p) {
      typedef vector<vector<float> > current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<vector<float> >

/********************************************************
* EdwTemplateDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEdwTemplateDict();

extern "C" void G__set_cpp_environmentEdwTemplateDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../src/EdwTemplate.cc");
  G__cpp_reset_tagtableEdwTemplateDict();
}
#include <new>
extern "C" int G__cpp_dllrevEdwTemplateDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EdwTemplate */
static int G__EdwTemplateDict_670_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdwTemplate* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdwTemplate[n];
     } else {
       p = new((void*) gvp) EdwTemplate[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdwTemplate;
     } else {
       p = new((void*) gvp) EdwTemplate;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EdwTemplateDictLN_EdwTemplate));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwTemplate*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwTemplate*) G__getstructoffset())->Initialize(
*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))
, (ULong64_t) G__ULonglong(libp->para[2]), (ULong64_t) G__ULonglong(libp->para[3])
, *((vector<Float_t>*) G__int(libp->para[4])), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (Int_t) G__int(libp->para[7])
, (Int_t) G__int(libp->para[8]), *((vector<Float_t>*) G__int(libp->para[9])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string* pobj;
         const string xobj = ((const EdwTemplate*) G__getstructoffset())->Channel();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string* pobj;
         const string xobj = ((const EdwTemplate*) G__getstructoffset())->Type();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const EdwTemplate*) G__getstructoffset())->Sign());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const EdwTemplate*) G__getstructoffset())->Pretrigger());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const EdwTemplate*) G__getstructoffset())->TraceLength());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const EdwTemplate*) G__getstructoffset())->IsTimeValid((ULong64_t) G__ULonglong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const EdwTemplate*) G__getstructoffset())->MinOffset());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const EdwTemplate*) G__getstructoffset())->MaxOffset());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<Float_t>* pobj;
         const vector<Float_t> xobj = ((const EdwTemplate*) G__getstructoffset())->GetOffsetFFT((Int_t) G__int(libp->para[0]));
         pobj = new vector<Float_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<Float_t>* pobj;
         const vector<Float_t> xobj = ((const EdwTemplate*) G__getstructoffset())->GetNonIntegerOffsetFFT((Float_t) G__double(libp->para[0]));
         pobj = new vector<Float_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<Float_t>* pobj;
         const vector<Float_t> xobj = ((const EdwTemplate*) G__getstructoffset())->GetKernel((Int_t) G__int(libp->para[0]));
         pobj = new vector<Float_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const EdwTemplate*) G__getstructoffset())->GetDenom((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwTemplate*) G__getstructoffset())->ComputeKernels(*((vector<Float_t>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      {
         const vector<Float_t>* pobj;
         const vector<Float_t> xobj = ((const EdwTemplate*) G__getstructoffset())->ComputeTrace((Float_t) G__double(libp->para[0]), (Bool_t) G__int(libp->para[1]));
         pobj = new vector<Float_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
      break;
   case 1:
      {
         const vector<Float_t>* pobj;
         const vector<Float_t> xobj = ((const EdwTemplate*) G__getstructoffset())->ComputeTrace((Float_t) G__double(libp->para[0]));
         pobj = new vector<Float_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const EdwTemplate*) G__getstructoffset())->PulseStandardIon((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const EdwTemplate*) G__getstructoffset())->PulseIonBB2((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const EdwTemplate*) G__getstructoffset())->PulseStandardChal((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const EdwTemplate*) G__getstructoffset())->PulseChalNTD((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EdwTemplate::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdwTemplate::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EdwTemplate::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EdwTemplate::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwTemplate*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdwTemplate::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdwTemplate::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdwTemplate::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwTemplateDict_670_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdwTemplate::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EdwTemplateDict_670_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EdwTemplate* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EdwTemplate(*(EdwTemplate*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EdwTemplateDictLN_EdwTemplate));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EdwTemplate G__TEdwTemplate;
static int G__EdwTemplateDict_670_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EdwTemplate*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EdwTemplate*) (soff+(sizeof(EdwTemplate)*i)))->~G__TEdwTemplate();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EdwTemplate*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EdwTemplate*) (soff))->~G__TEdwTemplate();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EdwTemplateDict_670_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdwTemplate* dest = (EdwTemplate*) G__getstructoffset();
   *dest = *(EdwTemplate*) libp->para[0].ref;
   const EdwTemplate& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EdwTemplate */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEdwTemplateDict {
 public:
  G__Sizep2memfuncEdwTemplateDict(): p(&G__Sizep2memfuncEdwTemplateDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEdwTemplateDict::*p)();
};

size_t G__get_sizep2memfuncEdwTemplateDict()
{
  G__Sizep2memfuncEdwTemplateDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEdwTemplateDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EdwTemplateDictLN_EdwTemplate))) {
     EdwTemplate *G__Lderived;
     G__Lderived=(EdwTemplate*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EdwTemplateDictLN_EdwTemplate),G__get_linked_tagnum(&G__EdwTemplateDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEdwTemplateDict() {

   /* Setting up typedef entry */
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BoloStr>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RunStr>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PeriodStr>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TemplateStr>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Float_t> >",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<float,allocator<float> > >",117,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EdwTemplate */
static void G__setup_memvarEdwTemplate(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EdwTemplateDictLN_EdwTemplate));
   { EdwTemplate *p; p=(EdwTemplate*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwTemplateDictLN_string),-1,-1,4,"fChannel=",0,"*< Template channel */");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwTemplateDictLN_string),-1,-1,4,"fType=",0,(char*)NULL);
   G__memvar_setup((void*)0,109,0,0,-1,G__defined_typename("ULong64_t"),-1,4,"fStartValidity=",0,"*< Period of validity */");
   G__memvar_setup((void*)0,109,0,0,-1,G__defined_typename("ULong64_t"),-1,4,"fEndValidity=",0,"*< Period of validity */");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fPretrigger=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"fTraceLength=",0,(char*)NULL);
   G__memvar_setup((void*)0,115,0,0,-1,G__defined_typename("Short_t"),-1,4,"fSign=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fNormalisation=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,4,"fCoefficients=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,4,"fTrace=",0,"*< Template trace*/");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,4,"fBinsOffsetFFT=",0,"*< List of bins for which the ffts are saved */");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),G__defined_typename("vector<vector<Float_t> >"),-1,4,"fTracesOffsetFFT=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<Float_t>"),-1,4,"fDenoms=",0,"*< kernel denominators */");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),G__defined_typename("vector<vector<Float_t> >"),-1,4,"fKernels=",0,"*< kernels */");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EdwTemplateDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEdwTemplateDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEdwTemplate(void) {
   /* EdwTemplate */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EdwTemplateDictLN_EdwTemplate));
   G__memfunc_setup("EdwTemplate",1116,G__EdwTemplateDict_670_0_1, 105, G__get_linked_tagnum(&G__EdwTemplateDictLN_EdwTemplate), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__EdwTemplateDict_670_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__EdwTemplateDict_670_0_3, 121, -1, -1, 0, 10, 1, 1, 0, 
"u 'string' - 0 - aChannel u 'string' - 0 - aType "
"m - 'ULong64_t' 0 - aTinf m - 'ULong64_t' 0 - aTsup "
"u 'vector<float,allocator<float> >' 'vector<Float_t>' 0 - aCoefs h - 'UInt_t' 0 - aLength "
"h - 'UInt_t' 0 - aPretrig i - 'Int_t' 0 - aOffsetMin "
"i - 'Int_t' 0 - aOffsetMax u 'vector<float,allocator<float> >' 'vector<Float_t>' 0 - aNoise", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Channel",697,G__EdwTemplateDict_670_0_4, 117, G__get_linked_tagnum(&G__EdwTemplateDictLN_string), -1, 0, 0, 1, 1, 8, "", "*< Channel */", (void*) NULL, 0);
   G__memfunc_setup("Type",418,G__EdwTemplateDict_670_0_5, 117, G__get_linked_tagnum(&G__EdwTemplateDictLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Sign",401,G__EdwTemplateDict_670_0_6, 115, -1, G__defined_typename("Short_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Pretrigger",1051,G__EdwTemplateDict_670_0_7, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TraceLength",1105,G__EdwTemplateDict_670_0_8, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsTimeValid",1083,G__EdwTemplateDict_670_0_9, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 8, "m - 'ULong64_t' 0 - aTime", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MinOffset",907,G__EdwTemplateDict_670_0_10, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MaxOffset",909,G__EdwTemplateDict_670_0_11, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetOffsetFFT",1127,G__EdwTemplateDict_670_0_12, 117, G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR), G__defined_typename("vector<Float_t>"), 0, 1, 1, 1, 8, "i - 'Int_t' 0 - aOffset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNonIntegerOffsetFFT",2144,G__EdwTemplateDict_670_0_13, 117, G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR), G__defined_typename("vector<Float_t>"), 0, 1, 1, 1, 8, "f - 'Float_t' 0 - aOffset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetKernel",897,G__EdwTemplateDict_670_0_14, 117, G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR), G__defined_typename("vector<Float_t>"), 0, 1, 1, 1, 8, "i - 'Int_t' 0 - aOffset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDenom",787,G__EdwTemplateDict_670_0_15, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 0 - aOffset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ComputeKernels",1457,G__EdwTemplateDict_670_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<float,allocator<float> >' 'vector<Float_t>' 0 - aNoise", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ComputeTrace",1228,G__EdwTemplateDict_670_0_17, 117, G__get_linked_tagnum(&G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR), G__defined_typename("vector<Float_t>"), 0, 2, 1, 1, 8, 
"f - 'Float_t' 0 - offset g - 'Bool_t' 0 '0' windowflag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PulseStandardIon",1632,G__EdwTemplateDict_670_0_18, 102, -1, G__defined_typename("Float_t"), 0, 2, 1, 1, 8, 
"f - 'Float_t' 0 - x f - 'Float_t' 0 - offset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PulseIonBB2",997,G__EdwTemplateDict_670_0_19, 102, -1, G__defined_typename("Float_t"), 0, 2, 1, 1, 8, 
"f - 'Float_t' 0 - x f - 'Float_t' 0 - offset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PulseStandardChal",1714,G__EdwTemplateDict_670_0_20, 102, -1, G__defined_typename("Float_t"), 0, 2, 1, 1, 8, 
"f - 'Float_t' 0 - x f - 'Float_t' 0 - offset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PulseChalNTD",1127,G__EdwTemplateDict_670_0_21, 102, -1, G__defined_typename("Float_t"), 0, 2, 1, 1, 8, 
"f - 'Float_t' 0 - x f - 'Float_t' 0 - offset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__EdwTemplateDict_670_0_22, 85, G__get_linked_tagnum(&G__EdwTemplateDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EdwTemplate::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EdwTemplateDict_670_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdwTemplate::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EdwTemplateDict_670_0_24, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EdwTemplate::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EdwTemplateDict_670_0_25, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EdwTemplate::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EdwTemplateDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EdwTemplateDict_670_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EdwTemplateDict_670_0_30, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdwTemplate::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EdwTemplateDict_670_0_31, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdwTemplate::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EdwTemplateDict_670_0_32, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdwTemplate::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EdwTemplateDict_670_0_33, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdwTemplate::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("EdwTemplate", 1116, G__EdwTemplateDict_670_0_34, (int) ('i'), G__get_linked_tagnum(&G__EdwTemplateDictLN_EdwTemplate), -1, 0, 1, 1, 1, 0, "u 'EdwTemplate' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EdwTemplate", 1242, G__EdwTemplateDict_670_0_35, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EdwTemplateDict_670_0_36, (int) ('u'), G__get_linked_tagnum(&G__EdwTemplateDictLN_EdwTemplate), -1, 1, 1, 1, 1, 0, "u 'EdwTemplate' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEdwTemplateDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEdwTemplateDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEdwTemplateDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EdwTemplateDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR = { "vector<BoloStr,allocator<BoloStr> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BoloStr,allocator<BoloStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR = { "vector<RunStr,allocator<RunStr> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<RunStr,allocator<RunStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR = { "vector<PeriodStr,allocator<PeriodStr> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<PeriodStr,allocator<PeriodStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR = { "vector<TemplateStr,allocator<TemplateStr> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TemplateStr,allocator<TemplateStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_EdwTemplate = { "EdwTemplate" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR = { "vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >" , 99 , -1 };
G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEdwTemplateDict() {
  G__EdwTemplateDictLN_TClass.tagnum = -1 ;
  G__EdwTemplateDictLN_TBuffer.tagnum = -1 ;
  G__EdwTemplateDictLN_TMemberInspector.tagnum = -1 ;
  G__EdwTemplateDictLN_TObject.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_string.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwTemplateDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EdwTemplateDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EdwTemplateDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EdwTemplateDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EdwTemplateDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EdwTemplateDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwTemplateDictLN_EdwTemplate.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR.tagnum = -1 ;
  G__EdwTemplateDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEdwTemplateDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_string);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_EdwTemplate),sizeof(EdwTemplate),-1,292096,(char*)NULL,G__setup_memvarEdwTemplate,G__setup_memfuncEdwTemplate);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwTemplateDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupEdwTemplateDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEdwTemplateDict()");
  G__set_cpp_environmentEdwTemplateDict();
  G__cpp_setup_tagtableEdwTemplateDict();

  G__cpp_setup_inheritanceEdwTemplateDict();

  G__cpp_setup_typetableEdwTemplateDict();

  G__cpp_setup_memvarEdwTemplateDict();

  G__cpp_setup_memfuncEdwTemplateDict();
  G__cpp_setup_globalEdwTemplateDict();
  G__cpp_setup_funcEdwTemplateDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEdwTemplateDict();
  return;
}
class G__cpp_setup_initEdwTemplateDict {
  public:
    G__cpp_setup_initEdwTemplateDict() { G__add_setup_func("EdwTemplateDict",(G__incsetup)(&G__cpp_setupEdwTemplateDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEdwTemplateDict() { G__remove_setup_func("EdwTemplateDict"); }
};
G__cpp_setup_initEdwTemplateDict G__cpp_setup_initializerEdwTemplateDict;

