/********************************************************************
* EdwTemplateDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EdwTemplateDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEdwTemplateDict();
extern void G__cpp_setup_inheritanceEdwTemplateDict();
extern void G__cpp_setup_typetableEdwTemplateDict();
extern void G__cpp_setup_memvarEdwTemplateDict();
extern void G__cpp_setup_globalEdwTemplateDict();
extern void G__cpp_setup_memfuncEdwTemplateDict();
extern void G__cpp_setup_funcEdwTemplateDict();
extern void G__set_cpp_environmentEdwTemplateDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/EdwTemplate.cc"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EdwTemplateDictLN_TClass;
extern G__linked_taginfo G__EdwTemplateDictLN_TBuffer;
extern G__linked_taginfo G__EdwTemplateDictLN_TMemberInspector;
extern G__linked_taginfo G__EdwTemplateDictLN_TObject;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_string;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwTemplateDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EdwTemplateDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EdwTemplateDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EdwTemplateDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EdwTemplateDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EdwTemplateDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwTemplateDictLN_EdwTemplate;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwTemplateDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__EdwTemplateDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
