/********************************************************************
* FitPulseDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error FitPulseDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFitPulseDict();
extern void G__cpp_setup_inheritanceFitPulseDict();
extern void G__cpp_setup_typetableFitPulseDict();
extern void G__cpp_setup_memvarFitPulseDict();
extern void G__cpp_setup_globalFitPulseDict();
extern void G__cpp_setup_memfuncFitPulseDict();
extern void G__cpp_setup_funcFitPulseDict();
extern void G__set_cpp_environmentFitPulseDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/FitPulse.cc"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FitPulseDictLN_TClass;
extern G__linked_taginfo G__FitPulseDictLN_TBuffer;
extern G__linked_taginfo G__FitPulseDictLN_TMemberInspector;
extern G__linked_taginfo G__FitPulseDictLN_TObject;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_string;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__FitPulseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__FitPulseDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__FitPulseDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__FitPulseDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__FitPulseDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_EdwPulse;
extern G__linked_taginfo G__FitPulseDictLN_EdwTemplate;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__FitPulseDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitPulseDictLN_FitPulse;

/* STUB derived class for protected member access */
