/********************************************************************
* NoiseSpectrumDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NoiseSpectrumDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNoiseSpectrumDict();
extern void G__cpp_setup_inheritanceNoiseSpectrumDict();
extern void G__cpp_setup_typetableNoiseSpectrumDict();
extern void G__cpp_setup_memvarNoiseSpectrumDict();
extern void G__cpp_setup_globalNoiseSpectrumDict();
extern void G__cpp_setup_memfuncNoiseSpectrumDict();
extern void G__cpp_setup_funcNoiseSpectrumDict();
extern void G__set_cpp_environmentNoiseSpectrumDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/NoiseSpectrum.cc"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NoiseSpectrumDictLN_TClass;
extern G__linked_taginfo G__NoiseSpectrumDictLN_TBuffer;
extern G__linked_taginfo G__NoiseSpectrumDictLN_TMemberInspector;
extern G__linked_taginfo G__NoiseSpectrumDictLN_TObject;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_string;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoiseSpectrumDictLN_NoiseSpectrum;

/* STUB derived class for protected member access */
