//
// File generated by rootcint at Fri Oct 31 11:01:41 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EdwEventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EdwEventDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void EdwEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EdwEvent(void *p = 0);
   static void *newArray_EdwEvent(Long_t size, void *p);
   static void delete_EdwEvent(void *p);
   static void deleteArray_EdwEvent(void *p);
   static void destruct_EdwEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::EdwEvent*)
   {
      ::EdwEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EdwEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EdwEvent", ::EdwEvent::Class_Version(), "./../src/EdwEvent.h", 8,
                  typeid(::EdwEvent), DefineBehavior(ptr, ptr),
                  &::EdwEvent::Dictionary, isa_proxy, 4,
                  sizeof(::EdwEvent) );
      instance.SetNew(&new_EdwEvent);
      instance.SetNewArray(&newArray_EdwEvent);
      instance.SetDelete(&delete_EdwEvent);
      instance.SetDeleteArray(&deleteArray_EdwEvent);
      instance.SetDestructor(&destruct_EdwEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::EdwEvent*)
   {
      return GenerateInitInstanceLocal((::EdwEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EdwEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *EdwEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *EdwEvent::Class_Name()
{
   return "EdwEvent";
}

//______________________________________________________________________________
const char *EdwEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::EdwEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EdwEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::EdwEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EdwEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::EdwEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EdwEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::EdwEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void EdwEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class EdwEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(EdwEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(EdwEvent::Class(),this);
   }
}

//______________________________________________________________________________
void EdwEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EdwEvent.
      TClass *R__cl = ::EdwEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPulses", (void*)&fPulses);
      R__insp.InspectMember("vector<EdwPulse>", (void*)&fPulses, "fPulses.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRun", (void*)&fRun);
      R__insp.InspectMember("string", (void*)&fRun, "fRun.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPartition", (void*)&fPartition);
      R__insp.InspectMember("string", (void*)&fPartition, "fPartition.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSambaNum", &fSambaNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDateSec", &fDateSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDateMuSec", &fDateMuSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fGigaStamp", &fGigaStamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTimeStamp", &fTimeStamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTriggerBit", (void*)&fTriggerBit);
      R__insp.InspectMember("vector<UInt_t>", (void*)&fTriggerBit, "fTriggerBit.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTemperature", &fTemperature);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_EdwEvent(void *p) {
      return  p ? new(p) ::EdwEvent : new ::EdwEvent;
   }
   static void *newArray_EdwEvent(Long_t nElements, void *p) {
      return p ? new(p) ::EdwEvent[nElements] : new ::EdwEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_EdwEvent(void *p) {
      delete ((::EdwEvent*)p);
   }
   static void deleteArray_EdwEvent(void *p) {
      delete [] ((::EdwEvent*)p);
   }
   static void destruct_EdwEvent(void *p) {
      typedef ::EdwEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::EdwEvent

namespace ROOT {
   void vectorlEEdwPulsegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEEdwPulsegR_Dictionary();
   static void *new_vectorlEEdwPulsegR(void *p = 0);
   static void *newArray_vectorlEEdwPulsegR(Long_t size, void *p);
   static void delete_vectorlEEdwPulsegR(void *p);
   static void deleteArray_vectorlEEdwPulsegR(void *p);
   static void destruct_vectorlEEdwPulsegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<EdwPulse>*)
   {
      vector<EdwPulse> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<EdwPulse>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<EdwPulse>", -2, "prec_stl/vector", 49,
                  typeid(vector<EdwPulse>), DefineBehavior(ptr, ptr),
                  0, &vectorlEEdwPulsegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<EdwPulse>) );
      instance.SetNew(&new_vectorlEEdwPulsegR);
      instance.SetNewArray(&newArray_vectorlEEdwPulsegR);
      instance.SetDelete(&delete_vectorlEEdwPulsegR);
      instance.SetDeleteArray(&deleteArray_vectorlEEdwPulsegR);
      instance.SetDestructor(&destruct_vectorlEEdwPulsegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<EdwPulse> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<EdwPulse>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEEdwPulsegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<EdwPulse>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEEdwPulsegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<EdwPulse> : new vector<EdwPulse>;
   }
   static void *newArray_vectorlEEdwPulsegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<EdwPulse>[nElements] : new vector<EdwPulse>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEEdwPulsegR(void *p) {
      delete ((vector<EdwPulse>*)p);
   }
   static void deleteArray_vectorlEEdwPulsegR(void *p) {
      delete [] ((vector<EdwPulse>*)p);
   }
   static void destruct_vectorlEEdwPulsegR(void *p) {
      typedef vector<EdwPulse> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<EdwPulse>

namespace ROOT {
   void vectorlEunsignedsPintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEunsignedsPintgR_Dictionary();
   static void *new_vectorlEunsignedsPintgR(void *p = 0);
   static void *newArray_vectorlEunsignedsPintgR(Long_t size, void *p);
   static void delete_vectorlEunsignedsPintgR(void *p);
   static void deleteArray_vectorlEunsignedsPintgR(void *p);
   static void destruct_vectorlEunsignedsPintgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<unsigned int>*)
   {
      vector<unsigned int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<unsigned int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<unsigned int>", -2, "vector.dll", 0,
                  typeid(vector<unsigned int>), DefineBehavior(ptr, ptr),
                  0, &vectorlEunsignedsPintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<unsigned int>) );
      instance.SetNew(&new_vectorlEunsignedsPintgR);
      instance.SetNewArray(&newArray_vectorlEunsignedsPintgR);
      instance.SetDelete(&delete_vectorlEunsignedsPintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEunsignedsPintgR);
      instance.SetDestructor(&destruct_vectorlEunsignedsPintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<unsigned int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<unsigned int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEunsignedsPintgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<unsigned int>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEunsignedsPintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned int> : new vector<unsigned int>;
   }
   static void *newArray_vectorlEunsignedsPintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned int>[nElements] : new vector<unsigned int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEunsignedsPintgR(void *p) {
      delete ((vector<unsigned int>*)p);
   }
   static void deleteArray_vectorlEunsignedsPintgR(void *p) {
      delete [] ((vector<unsigned int>*)p);
   }
   static void destruct_vectorlEunsignedsPintgR(void *p) {
      typedef vector<unsigned int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<unsigned int>

/********************************************************
* EdwEventDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEdwEventDict();

extern "C" void G__set_cpp_environmentEdwEventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../src/EdwEvent.cc");
  G__cpp_reset_tagtableEdwEventDict();
}
#include <new>
extern "C" int G__cpp_dllrevEdwEventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EdwEvent */
static int G__EdwEventDict_671_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdwEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdwEvent[n];
     } else {
       p = new((void*) gvp) EdwEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EdwEvent;
     } else {
       p = new((void*) gvp) EdwEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EdwEventDictLN_EdwEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const EdwEvent*) G__getstructoffset())->NbPulses());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EdwEvent*) G__getstructoffset())->Pulse((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EdwEvent*) G__getstructoffset())->Pulse(*((string*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->AddPulse(*((EdwPulse*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((EdwEvent*) G__getstructoffset())->Dump(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      ((EdwEvent*) G__getstructoffset())->Dump(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      ((EdwEvent*) G__getstructoffset())->Dump();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string* pobj;
         const string xobj = ((const EdwEvent*) G__getstructoffset())->Run();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string* pobj;
         const string xobj = ((const EdwEvent*) G__getstructoffset())->Partition();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const EdwEvent*) G__getstructoffset())->SambaNum());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letULonglong(result7, 109, (G__uint64) ((const EdwEvent*) G__getstructoffset())->DateSec());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const EdwEvent*) G__getstructoffset())->DateMuSec());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letULonglong(result7, 109, (G__uint64) ((const EdwEvent*) G__getstructoffset())->TimeStamp());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const EdwEvent*) G__getstructoffset())->GigaStamp());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const EdwEvent*) G__getstructoffset())->Temperature());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const EdwEvent*) G__getstructoffset())->TriggerBit((UInt_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<UInt_t>* pobj;
         const vector<UInt_t> xobj = ((const EdwEvent*) G__getstructoffset())->TriggerBit();
         pobj = new vector<UInt_t>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->SetSambaNum((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->SetDateSec((ULong64_t) G__ULonglong(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->SetDateMuSec((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->SetRun(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->SetPartition(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->SetGigaStamp((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->SetTimeStamp((ULong64_t) G__ULonglong(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->SetTriggerBit((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->SetTemperature((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EdwEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdwEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EdwEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EdwEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EdwEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdwEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdwEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EdwEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EdwEventDict_671_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EdwEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EdwEventDict_671_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EdwEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EdwEvent(*(EdwEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EdwEventDictLN_EdwEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EdwEvent G__TEdwEvent;
static int G__EdwEventDict_671_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EdwEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EdwEvent*) (soff+(sizeof(EdwEvent)*i)))->~G__TEdwEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EdwEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EdwEvent*) (soff))->~G__TEdwEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EdwEventDict_671_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EdwEvent* dest = (EdwEvent*) G__getstructoffset();
   *dest = *(EdwEvent*) libp->para[0].ref;
   const EdwEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EdwEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEdwEventDict {
 public:
  G__Sizep2memfuncEdwEventDict(): p(&G__Sizep2memfuncEdwEventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEdwEventDict::*p)();
};

size_t G__get_sizep2memfuncEdwEventDict()
{
  G__Sizep2memfuncEdwEventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEdwEventDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EdwEventDictLN_EdwEvent))) {
     EdwEvent *G__Lderived;
     G__Lderived=(EdwEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EdwEventDictLN_EdwEvent),G__get_linked_tagnum(&G__EdwEventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEdwEventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EdwEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EdwEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EdwEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EdwEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EdwEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__EdwEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EdwEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EdwEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__EdwEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EdwEventDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EdwEventDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EdwEventDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EdwEventDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__EdwEventDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BoloStr>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RunStr>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PeriodStr>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TemplateStr>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Short_t>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEshortcOallocatorlEshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<EdwPulse>",117,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEEdwPulsecOallocatorlEEdwPulsegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEEdwPulsecOallocatorlEEdwPulsegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEEdwPulsecOallocatorlEEdwPulsegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EdwEventDictLN_reverse_iteratorlEvectorlEEdwPulsecOallocatorlEEdwPulsegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEEdwPulsecOallocatorlEEdwPulsegRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EdwEvent */
static void G__setup_memvarEdwEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EdwEventDictLN_EdwEvent));
   { EdwEvent *p; p=(EdwEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEEdwPulsecOallocatorlEEdwPulsegRsPgR),G__defined_typename("vector<EdwPulse>"),-1,4,"fPulses=",0,"*< Array of pulses (each event may have an arbitrary number of pulses) */");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwEventDictLN_string),-1,-1,4,"fRun=",0,"*< Run name */");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwEventDictLN_string),-1,-1,4,"fPartition=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"fSambaNum=",0,"*< Samba event num */");
   G__memvar_setup((void*)0,109,0,0,-1,G__defined_typename("ULong64_t"),-1,4,"fDateSec=",0,"*< Event unix time */");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fDateMuSec=",0,"*< Microsec time */");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fGigaStamp=",0,(char*)NULL);
   G__memvar_setup((void*)0,109,0,0,-1,G__defined_typename("ULong64_t"),-1,4,"fTimeStamp=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<UInt_t>"),-1,4,"fTriggerBit=",0,"*< Bit trigger encoding */");
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fTemperature=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EdwEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEdwEventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEdwEvent(void) {
   /* EdwEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EdwEventDictLN_EdwEvent));
   G__memfunc_setup("EdwEvent",802,G__EdwEventDict_671_0_1, 105, G__get_linked_tagnum(&G__EdwEventDictLN_EdwEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NbPulses",812,G__EdwEventDict_671_0_2, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Pulse",521,G__EdwEventDict_671_0_3, 85, G__get_linked_tagnum(&G__EdwEventDictLN_EdwPulse), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Pulse",521,G__EdwEventDict_671_0_4, 85, G__get_linked_tagnum(&G__EdwEventDictLN_EdwPulse), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - aChannel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddPulse",786,G__EdwEventDict_671_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "u 'EdwPulse' - 0 - aPulse", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Dump",406,G__EdwEventDict_671_0_6, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 '\"None\"' aFile u 'string' - 0 '\"all\"' aChannel", "*< Prints header and all traces to standard output */", (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__EdwEventDict_671_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", "*< Resets the event */", (void*) NULL, 0);
   G__memfunc_setup("Run",309,G__EdwEventDict_671_0_8, 117, G__get_linked_tagnum(&G__EdwEventDictLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Partition",954,G__EdwEventDict_671_0_9, 117, G__get_linked_tagnum(&G__EdwEventDictLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SambaNum",788,G__EdwEventDict_671_0_10, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DateSec",665,G__EdwEventDict_671_0_11, 109, -1, G__defined_typename("ULong64_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DateMuSec",859,G__EdwEventDict_671_0_12, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TimeStamp",916,G__EdwEventDict_671_0_13, 109, -1, G__defined_typename("ULong64_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GigaStamp",893,G__EdwEventDict_671_0_14, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Temperature",1166,G__EdwEventDict_671_0_15, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TriggerBit",1011,G__EdwEventDict_671_0_16, 104, -1, G__defined_typename("UInt_t"), 0, 1, 1, 1, 8, "h - 'UInt_t' 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TriggerBit",1011,G__EdwEventDict_671_0_17, 117, G__get_linked_tagnum(&G__EdwEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR), G__defined_typename("vector<UInt_t>"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSambaNum",1088,G__EdwEventDict_671_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDateSec",965,G__EdwEventDict_671_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "m - 'ULong64_t' 0 - sec", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDateMuSec",1159,G__EdwEventDict_671_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - musec", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRun",609,G__EdwEventDict_671_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - run", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPartition",1254,G__EdwEventDict_671_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - aPartition", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGigaStamp",1193,G__EdwEventDict_671_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - gigast", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimeStamp",1216,G__EdwEventDict_671_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "m - 'ULong64_t' 0 - stamp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTriggerBit",1311,G__EdwEventDict_671_0_25, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - 'UInt_t' 0 - aNum h - 'UInt_t' 0 - aBit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTemperature",1466,G__EdwEventDict_671_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - tempe", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__EdwEventDict_671_0_27, 85, G__get_linked_tagnum(&G__EdwEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EdwEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EdwEventDict_671_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdwEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EdwEventDict_671_0_29, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EdwEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EdwEventDict_671_0_30, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EdwEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EdwEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EdwEventDict_671_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EdwEventDict_671_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdwEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EdwEventDict_671_0_36, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdwEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EdwEventDict_671_0_37, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EdwEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EdwEventDict_671_0_38, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EdwEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("EdwEvent", 802, G__EdwEventDict_671_0_39, (int) ('i'), G__get_linked_tagnum(&G__EdwEventDictLN_EdwEvent), -1, 0, 1, 1, 1, 0, "u 'EdwEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EdwEvent", 928, G__EdwEventDict_671_0_40, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EdwEventDict_671_0_41, (int) ('u'), G__get_linked_tagnum(&G__EdwEventDictLN_EdwEvent), -1, 1, 1, 1, 1, 0, "u 'EdwEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEdwEventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEdwEventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEdwEventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EdwEventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EdwEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR = { "vector<BoloStr,allocator<BoloStr> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BoloStr,allocator<BoloStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR = { "vector<RunStr,allocator<RunStr> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<RunStr,allocator<RunStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR = { "vector<PeriodStr,allocator<PeriodStr> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<PeriodStr,allocator<PeriodStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR = { "vector<TemplateStr,allocator<TemplateStr> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TemplateStr,allocator<TemplateStr> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_EdwPulse = { "EdwPulse" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_EdwEvent = { "EdwEvent" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_vectorlEEdwPulsecOallocatorlEEdwPulsegRsPgR = { "vector<EdwPulse,allocator<EdwPulse> >" , 99 , -1 };
G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEEdwPulsecOallocatorlEEdwPulsegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<EdwPulse,allocator<EdwPulse> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEdwEventDict() {
  G__EdwEventDictLN_TClass.tagnum = -1 ;
  G__EdwEventDictLN_TBuffer.tagnum = -1 ;
  G__EdwEventDictLN_TMemberInspector.tagnum = -1 ;
  G__EdwEventDictLN_TObject.tagnum = -1 ;
  G__EdwEventDictLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_string.tagnum = -1 ;
  G__EdwEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EdwEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EdwEventDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EdwEventDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EdwEventDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EdwEventDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__EdwEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwEventDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwEventDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwEventDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwEventDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwEventDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EdwEventDictLN_EdwPulse.tagnum = -1 ;
  G__EdwEventDictLN_EdwEvent.tagnum = -1 ;
  G__EdwEventDictLN_vectorlEEdwPulsecOallocatorlEEdwPulsegRsPgR.tagnum = -1 ;
  G__EdwEventDictLN_reverse_iteratorlEvectorlEEdwPulsecOallocatorlEEdwPulsegRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEdwEventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_string);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_EdwPulse);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EdwEventDictLN_EdwEvent),sizeof(EdwEvent),-1,292096,(char*)NULL,G__setup_memvarEdwEvent,G__setup_memfuncEdwEvent);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_vectorlEEdwPulsecOallocatorlEEdwPulsegRsPgR);
   G__get_linked_tagnum_fwd(&G__EdwEventDictLN_reverse_iteratorlEvectorlEEdwPulsecOallocatorlEEdwPulsegRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupEdwEventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEdwEventDict()");
  G__set_cpp_environmentEdwEventDict();
  G__cpp_setup_tagtableEdwEventDict();

  G__cpp_setup_inheritanceEdwEventDict();

  G__cpp_setup_typetableEdwEventDict();

  G__cpp_setup_memvarEdwEventDict();

  G__cpp_setup_memfuncEdwEventDict();
  G__cpp_setup_globalEdwEventDict();
  G__cpp_setup_funcEdwEventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEdwEventDict();
  return;
}
class G__cpp_setup_initEdwEventDict {
  public:
    G__cpp_setup_initEdwEventDict() { G__add_setup_func("EdwEventDict",(G__incsetup)(&G__cpp_setupEdwEventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEdwEventDict() { G__remove_setup_func("EdwEventDict"); }
};
G__cpp_setup_initEdwEventDict G__cpp_setup_initializerEdwEventDict;

