/********************************************************************
* EdwEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EdwEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEdwEventDict();
extern void G__cpp_setup_inheritanceEdwEventDict();
extern void G__cpp_setup_typetableEdwEventDict();
extern void G__cpp_setup_memvarEdwEventDict();
extern void G__cpp_setup_globalEdwEventDict();
extern void G__cpp_setup_memfuncEdwEventDict();
extern void G__cpp_setup_funcEdwEventDict();
extern void G__set_cpp_environmentEdwEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/EdwEvent.cc"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EdwEventDictLN_TClass;
extern G__linked_taginfo G__EdwEventDictLN_TBuffer;
extern G__linked_taginfo G__EdwEventDictLN_TMemberInspector;
extern G__linked_taginfo G__EdwEventDictLN_TObject;
extern G__linked_taginfo G__EdwEventDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_string;
extern G__linked_taginfo G__EdwEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EdwEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EdwEventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EdwEventDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EdwEventDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EdwEventDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__EdwEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwEventDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwEventDictLN_vectorlEBoloStrcOallocatorlEBoloStrgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEBoloStrcOallocatorlEBoloStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwEventDictLN_vectorlERunStrcOallocatorlERunStrgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlERunStrcOallocatorlERunStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwEventDictLN_vectorlEPeriodStrcOallocatorlEPeriodStrgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEPeriodStrcOallocatorlEPeriodStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwEventDictLN_vectorlETemplateStrcOallocatorlETemplateStrgRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlETemplateStrcOallocatorlETemplateStrgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EdwEventDictLN_EdwPulse;
extern G__linked_taginfo G__EdwEventDictLN_EdwEvent;
extern G__linked_taginfo G__EdwEventDictLN_vectorlEEdwPulsecOallocatorlEEdwPulsegRsPgR;
extern G__linked_taginfo G__EdwEventDictLN_reverse_iteratorlEvectorlEEdwPulsecOallocatorlEEdwPulsegRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
